1. unity3d ubuntu 설치
https://askubuntu.com/questions/1077816/how-to-install-unity3d-on-ubuntu-18-04 
이후 터미널에 unity3d 라고 치면 실행 됨. 


2. unity ml agnet 설치 
//설치는 아래 두 자료 섞어 참조 
//https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md
//https://www.youtube.com/watch?v=siy8qVFxwPs&list=PLctzObGsrjfwYHL1obWlVdPRbpubkuKWp&index=2

//ml agent code 다운 로드 
git clone https://github.com/Unity-Technologies/ml-agents.git

//python 3.6.X 설치 _ 3.5나 3.7 안됨 반드시 3.6.X만 설치 
//https://packaging.python.org/guides/installing-using-linux-tools/#installing-pip-setuptools-wheel-with-linux-package-managers
sudo apt install python3-venv python3-pip

//python3 --version  으로 python3 설치 확인 
hyunoklee@hyunoklee:~/Downloads$ python3 --version
Python 3.6.7


//파이썬3 용 pip upgrade
pip3 install --upgrade pip
-> 하기만 이거 하고 다음 step 에서 ImportError: cannot import name 'main' erro 발생하는 것 같음 
-> 다음 스탭서 erro 발생시 재설치 sudo python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall

//필요 dependency 설치  --> 여기서 tensor flow ? mlagents-learn 도 설치 하나  ?
cd ~/ml-agents/ml-agents
pip3 install -e .
~/ml-agents/ml-agents-envs
pip3 install -e ./

reboot 후
mlagents-learn --help 실행하면 관련 명령어 나와야함.  

그런데 안되면 위처럼 코드 래밸서 설치 외헤 bin 설치 하는 방법도 있음 
//ml agent를 다움받은 code를 통해서가 아닌 bin으로 설치 
//pip3 install mlagents
reboot 후 
mlagents-learn --help 실행하면 관련 명령어 나와야함.  

3. 실행 시킴  
3D ball 기본예제 아래 명령어 실행시 erro 발생 원인 찾아야함. 
mlagents-learn config/trainer_config.yaml --run-id=<run-identifier> --train


추가 참고 자료 
https://ridohee.tistory.com/20?category=841803
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md

/////////
~/ml-agents$ mlagents-learn config/trainer_config.yaml --run-id=test --train
~/UnityMlBall$ mlagents-learn --train --slow trainer_config.yaml
///////

/home/hyunoklee/.local/lib/python3.6/site-packages/mlagents/trainers/learn.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  trainer_config = yaml.load(data_file)
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hyunoklee/.local/lib/python3.6/site-packages/mlagents/envs/subprocess_environment.py", line 53, in worker
    env = env_factory(worker_id)
  File "/home/hyunoklee/.local/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 192, in create_unity_environment
    base_port=start_port
  File "/home/hyunoklee/.local/lib/python3.6/site-packages/mlagents/envs/environment.py", line 76, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "/home/hyunoklee/.local/lib/python3.6/site-packages/mlagents/envs/environment.py", line 538, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "/home/hyunoklee/.local/lib/python3.6/site-packages/mlagents/envs/rpc_communicator.py", line 80, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Academy's Broadcast Hub is configured correctly
	 The Agents are linked to the appropriate Brains
	 The environment and the Python interface have compatible versions.
Traceback (most recent call last):
  File "/home/hyunoklee/.local/bin/mlagents-learn", line 11, in <module>
    sys.exit(main())
  File "/home/hyunoklee/.local/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "/home/hyunoklee/.local/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 88, in run_training
    keep_checkpoints, lesson, env.external_brains,
  File "/home/hyunoklee/.local/lib/python3.6/site-packages/mlagents/envs/subprocess_environment.py", line 173, in external_brains
    return self.envs[0].recv().payload
  File "/home/hyunoklee/.local/lib/python3.6/site-packages/mlagents/envs/subprocess_environment.py", line 38, in recv
    response: EnvironmentResponse = self.conn.recv()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

